module.exports = {
  isString: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotString: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isArray: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotArray: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isObject: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotObject: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isNull: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotNull: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isUndefined: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotUndefined: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isBoolean: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotBoolean: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isTrue: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotTrue: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isFalse: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotFalse: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isRegExp: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotRegExp: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isNumber: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotNumber: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isNaN: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotNaN: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isFunction: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotFunction: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isGenerator: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotGenerator: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isPromise: [
    { input: 'Promise.resolve()', 'result': 'pass' },
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotPromise: [
    { input: 'Promise.resolve()', 'result': 'fail' },
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isClass: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isNotClass: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isAny: [
    { input: '"foo"', 'result': 'pass', args: [['string', 'number']] },
    { input: '""', 'result': 'pass', args: [['string', 'number']] },
    { input: '`template str`', 'result': 'pass', args: [['string', 'number']] },
    { input: '123', 'result': 'pass', args: [['string', 'number']] },
    { input: '1.23', 'result': 'pass', args: [['string', 'number']] },
    { input: 'null', 'result': 'fail', args: [['string', 'number']] },
    { input: 'undefined', 'result': 'fail', args: [['string', 'number']] },
    { input: 'true', 'result': 'fail', args: [['string', 'number']] },
    { input: 'false', 'result': 'fail', args: [['string', 'number']] },
    { input: 'NaN', 'result': 'fail', args: [['string', 'number']] },
    { input: '[]', 'result': 'fail', args: [['string', 'number']] },
    { input: '{}', 'result': 'fail', args: [['string', 'number']] },
    { input: '/[a-z]/', 'result': 'fail', args: [['string', 'number']] },
    { input: 'new Date()', 'result': 'fail', args: [['string', 'number']] },
    { input: 'function() {}', 'result': 'fail', args: [['string', 'number']] },
    { input: '() => {}', 'result': 'fail', args: [['string', 'number']] },
    { input: 'function* () {}', 'result': 'fail', args: [['string', 'number']] },
    { input: 'class {}', 'result': 'fail', args: [['string', 'number']] }
  ],
  isNotAny: [
    { input: '"foo"', 'result': 'fail', args: [['string', 'number']] },
    { input: '""', 'result': 'fail', args: [['string', 'number']] },
    { input: '`template str`', 'result': 'fail', args: [['string', 'number']] },
    { input: '123', 'result': 'fail', args: [['string', 'number']] },
    { input: '1.23', 'result': 'fail', args: [['string', 'number']] },
    { input: 'null', 'result': 'pass', args: [['string', 'number']] },
    { input: 'undefined', 'result': 'pass', args: [['string', 'number']] },
    { input: 'true', 'result': 'pass', args: [['string', 'number']] },
    { input: 'false', 'result': 'pass', args: [['string', 'number']] },
    { input: 'NaN', 'result': 'pass', args: [['string', 'number']] },
    { input: '[]', 'result': 'pass', args: [['string', 'number']] },
    { input: '{}', 'result': 'pass', args: [['string', 'number']] },
    { input: '/[a-z]/', 'result': 'pass', args: [['string', 'number']] },
    { input: 'new Date()', 'result': 'pass', args: [['string', 'number']] },
    { input: 'function fn() {}', 'result': 'pass', args: [['string', 'number']] },
    { input: '() => {}', 'result': 'pass', args: [['string', 'number']] },
    { input: 'function* () {}', 'result': 'pass', args: [['string', 'number']] },
    { input: 'class {}', 'result': 'pass', args: [['string', 'number']] }
  ],
  isTruthy: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isFalsy: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function fn() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isEmpty: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotEmpty: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isDate: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'pass' },
    { input: '"Thu Feb 02 2017 20:18:23 GMT+0100 (CET)"', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotDate: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'fail' },
    { input: '"Thu Feb 02 2017 20:18:23 GMT+0100 (CET)"', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isDateString: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: '"Thu Feb 02 2017 20:18:23 GMT+0100 (CET)"', 'result': 'pass' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotDateString: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: '"Thu Feb 02 2017 20:18:23 GMT+0100 (CET)"', 'result': 'fail' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isJSON: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '{\"foo\":\"bar\"}', 'result': 'pass' },
    { input: '"{\\\"foo\\\":\\\"bar\\\"}"', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotJSON: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '{\"foo\":\"bar\"}', 'result': 'fail' },
    { input: '"{\\\"foo\\\":\\\"bar\\\"}"', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ],
  isJSONString: [
    { input: '"foo"', 'result': 'fail' },
    { input: '""', 'result': 'fail' },
    { input: '`template str`', 'result': 'fail' },
    { input: '123', 'result': 'fail' },
    { input: '1.23', 'result': 'fail' },
    { input: 'null', 'result': 'fail' },
    { input: 'undefined', 'result': 'fail' },
    { input: 'true', 'result': 'fail' },
    { input: 'false', 'result': 'fail' },
    { input: 'NaN', 'result': 'fail' },
    { input: '[]', 'result': 'fail' },
    { input: '{}', 'result': 'fail' },
    { input: '"{\\\"foo\\\":\\\"bar\\\"}"', 'result': 'pass' },
    { input: '/[a-z]/', 'result': 'fail' },
    { input: 'new Date()', 'result': 'fail' },
    { input: 'function() {}', 'result': 'fail' },
    { input: '() => {}', 'result': 'fail' },
    { input: 'function* () {}', 'result': 'fail' },
    { input: 'class {}', 'result': 'fail' }
  ],
  isNotJSONString: [
    { input: '"foo"', 'result': 'pass' },
    { input: '""', 'result': 'pass' },
    { input: '`template str`', 'result': 'pass' },
    { input: '123', 'result': 'pass' },
    { input: '1.23', 'result': 'pass' },
    { input: 'null', 'result': 'pass' },
    { input: 'undefined', 'result': 'pass' },
    { input: 'true', 'result': 'pass' },
    { input: 'false', 'result': 'pass' },
    { input: 'NaN', 'result': 'pass' },
    { input: '[]', 'result': 'pass' },
    { input: '{}', 'result': 'pass' },
    { input: '"{\\\"foo\\\":\\\"bar\\\"}"', 'result': 'fail' },
    { input: '/[a-z]/', 'result': 'pass' },
    { input: 'new Date()', 'result': 'pass' },
    { input: 'function fn() {}', 'result': 'pass' },
    { input: '() => {}', 'result': 'pass' },
    { input: 'function* () {}', 'result': 'pass' },
    { input: 'class {}', 'result': 'pass' }
  ]
};
